In [11]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [13]:
df = pd.read_csv(r"D:\c drive all downloads\Churn_Modelling.csv")

In [14]:
df.head(3)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1

In [15]:
df = df.drop(["Surname","Geography","Gender"],axis=1)

In [16]:
df.isnull().sum()

RowNumber          0
CustomerId         0
CreditScore        0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [17]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [18]:
ss = StandardScaler()
x = pd.DataFrame(ss.fit_transform(x),columns=x.columns)

In [19]:
x

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,-1.731878,-0.783213,-0.326221,0.293517,-1.041760,-1.225848,-0.911583,0.646092,0.970243,0.021886
1,-1.731531,-0.606534,-0.440036,0.198164,-1.387538,0.117350,-0.911583,-1.547768,0.970243,0.216534
2,-1.731185,-0.995885,-1.536794,0.293517,1.032908,1.333053,2.527057,0.646092,-1.030670,0.240687
3,-1.730838,0.144767,0.501521,0.007457,-1.387538,-1.225848,0.807737,-1.547768,-1.030670,-0.108918
4,-1.730492,0.652659,2.063884,0.388871,-1.041760,0.785728,-0.911583,0.646092,0.970243,-0.365276
...,...,...,...,...,...,...,...,...,...,...
9995,1.730492,-1.177652,1.246488,0.007457,-0.004426,-1.225848,0.807737,0.646092,-1.030670,-0.066419
9996,1.730838,-1.682806,-1.391939,-0.373958,1.724464,-0.306379,-0.911583,0.646092,0.970243,0.027988
9997,1.731185,-1.479282,0.604988,-0.278604,0.687130,-1.225848,-0.911583,-1.547768,0.970243,-1.008643
9998,1.731531,-0.119356,1.256835,0.293517,-0.695982,-0.022608,0.807737,0.646092,-1.030670,-0.125231
9999,1.731878,-0.870559,1.463771,-1.041433,-0.350204,0.859965,-0.911583,0.646092,-1.030670,-1.076370

In [20]:
x.shape

(10000, 10)

In [21]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [22]:
x_train.shape

(8000, 10)

In [23]:
x_test

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
6252,0.433879,-0.047942,-0.564197,-0.660018,-0.695982,0.324119,0.807737,-1.547768,-1.030670,-1.013811
4684,-0.109292,0.639799,-0.284834,0.388871,-1.387538,-1.225848,0.807737,0.646092,0.970243,0.804921
1731,-1.132242,0.428032,-0.512463,0.484225,-0.350204,-1.225848,0.807737,0.646092,-1.030670,-0.722147
4742,-0.089201,0.989724,-1.495407,1.914528,1.032908,0.683816,0.807737,0.646092,0.970243,1.227481
4521,-0.165757,-0.584472,-0.936681,-1.136786,0.687130,0.777477,-0.911583,0.646092,0.970243,0.253524
...,...,...,...,...,...,...,...,...,...,...
6412,0.489304,-1.278399,-0.502117,1.342407,-0.004426,0.349118,-0.911583,-1.547768,0.970243,-0.957298
8285,1.138131,-1.644728,-0.429689,-1.327494,1.724464,-1.225848,-0.911583,-1.547768,0.970243,0.170498
7853,0.988481,0.774801,0.822271,0.770285,0.687130,-1.225848,-0.911583,0.646092,-1.030670,-1.160142
1095,-1.352558,-0.025852,0.429093,-0.946079,-0.350204,-1.225848,-0.911583,0.646092,-1.030670,-0.405759
6929,0.668398,-0.546533,-0.233100,0.007457,-1.387538,0.622738,-0.911583,0.646092,0.970243,0.131879

In [27]:
import tensorflow

In [43]:
from keras.layers import Dense
from keras.models import Sequential

In [44]:
ann = Sequential()

In [45]:
ann.add(Dense(8,input_dim=10,activation='relu'))
ann.add(Dense(4,activation='relu'))
ann.add(Dense(2,activation='relu'))
ann.add(Dense(1,activation='sigmoid'))

In [31]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [32]:
ann.fit(x_train,y_train,batch_size=100,epochs=50)

Epoch 1/50
80/80 [==============================] - 1s 2ms/step - loss: 0.8092 - accuracy: 0.4999
Epoch 2/50
80/80 [==============================] - 0s 2ms/step - loss: 0.6732 - accuracy: 0.7434
Epoch 3/50
80/80 [==============================] - 0s 2ms/step - loss: 0.6470 - accuracy: 0.7912
Epoch 4/50
80/80 [==============================] - 0s 2ms/step - loss: 0.6291 - accuracy: 0.8010
Epoch 5/50
80/80 [==============================] - 0s 2ms/step - loss: 0.6132 - accuracy: 0.8031
Epoch 6/50
80/80 [==============================] - 0s 2ms/step - loss: 0.5986 - accuracy: 0.8062
Epoch 7/50
80/80 [==============================] - 0s 2ms/step - loss: 0.5847 - accuracy: 0.8091
Epoch 8/50
80/80 [==============================] - 0s 3ms/step - loss: 0.5712 - accuracy: 0.8109
Epoch 9/50
80/80 [==============================] - 0s 3ms/step - loss: 0.5582 - accuracy: 0.8145
Epoch 10/50
80/80 [==============================] - 0s 2ms/step - loss: 0.5456 - accuracy: 0.8190
Epoch 11/50
80/80 [==============================] - 0s 2ms/step - loss: 0.5339 - accuracy: 0.8224
Epoch 12/50
80/80 [==============================] - 0s 2ms/step - loss: 0.5231 - accuracy: 0.8249
Epoch 13/50
80/80 [==============================] - 0s 2ms/step - loss: 0.5135 - accuracy: 0.8254
Epoch 14/50
80/80 [==============================] - 0s 2ms/step - loss: 0.5046 - accuracy: 0.8284
Epoch 15/50
80/80 [==============================] - 0s 2ms/step - loss: 0.4967 - accuracy: 0.8282
Epoch 16/50
80/80 [==============================] - 0s 2ms/step - loss: 0.4893 - accuracy: 0.8304
Epoch 17/50
80/80 [==============================] - 0s 2ms/step - loss: 0.4824 - accuracy: 0.8299
Epoch 18/50
80/80 [==============================] - 0s 2ms/step - loss: 0.4764 - accuracy: 0.8316
Epoch 19/50
80/80 [==============================] - 0s 2ms/step - loss: 0.4705 - accuracy: 0.8321
Epoch 20/50
80/80 [==============================] - 0s 2ms/step - loss: 0.4654 - accuracy: 0.8324
Epoch 21/50
80/80 [==============================] - 0s 2ms/step - loss: 0.4604 - accuracy: 0.8346
Epoch 22/50
80/80 [==============================] - 0s 3ms/step - loss: 0.4559 - accuracy: 0.8356
Epoch 23/50
80/80 [==============================] - 0s 2ms/step - loss: 0.4514 - accuracy: 0.8364
Epoch 24/50
80/80 [==============================] - 0s 2ms/step - loss: 0.4474 - accuracy: 0.8364
Epoch 25/50
80/80 [==============================] - 0s 2ms/step - loss: 0.4432 - accuracy: 0.8366
Epoch 26/50
80/80 [==============================] - 0s 2ms/step - loss: 0.4391 - accuracy: 0.8399
Epoch 27/50
80/80 [==============================] - 0s 3ms/step - loss: 0.4353 - accuracy: 0.8410
Epoch 28/50
80/80 [==============================] - 0s 2ms/step - loss: 0.4311 - accuracy: 0.8414
Epoch 29/50
80/80 [==============================] - 0s 2ms/step - loss: 0.4268 - accuracy: 0.8435
Epoch 30/50
80/80 [==============================] - 0s 2ms/step - loss: 0.4220 - accuracy: 0.8461
Epoch 31/50
80/80 [==============================] - 0s 2ms/step - loss: 0.4170 - accuracy: 0.8478
Epoch 32/50
80/80 [==============================] - 0s 2ms/step - loss: 0.4124 - accuracy: 0.8511
Epoch 33/50
80/80 [==============================] - 0s 2ms/step - loss: 0.4074 - accuracy: 0.8529
Epoch 34/50
80/80 [==============================] - 0s 2ms/step - loss: 0.4034 - accuracy: 0.8547
Epoch 35/50
80/80 [==============================] - 0s 2ms/step - loss: 0.4000 - accuracy: 0.8561
Epoch 36/50
80/80 [==============================] - 0s 2ms/step - loss: 0.3973 - accuracy: 0.8541
Epoch 37/50
80/80 [==============================] - 0s 2ms/step - loss: 0.3956 - accuracy: 0.8551
Epoch 38/50
80/80 [==============================] - 0s 2ms/step - loss: 0.3939 - accuracy: 0.8551
Epoch 39/50
80/80 [==============================] - 0s 2ms/step - loss: 0.3925 - accuracy: 0.8541
Epoch 40/50
80/80 [==============================] - 0s 1ms/step - loss: 0.3914 - accuracy: 0.8560
Epoch 41/50
80/80 [==============================] - 0s 2ms/step - loss: 0.3905 - accuracy: 0.8543
Epoch 42/50
80/80 [==============================] - 0s 2ms/step - loss: 0.3896 - accuracy: 0.8556
Epoch 43/50
80/80 [==============================] - 0s 2ms/step - loss: 0.3891 - accuracy: 0.8558
Epoch 44/50
80/80 [==============================] - 0s 2ms/step - loss: 0.3887 - accuracy: 0.8556
Epoch 45/50
80/80 [==============================] - 0s 2ms/step - loss: 0.3875 - accuracy: 0.8556
Epoch 46/50
80/80 [==============================] - 0s 2ms/step - loss: 0.3875 - accuracy: 0.8575
Epoch 47/50
80/80 [==============================] - 0s 2ms/step - loss: 0.3868 - accuracy: 0.8562
Epoch 48/50
80/80 [==============================] - 0s 2ms/step - loss: 0.3864 - accuracy: 0.8559
Epoch 49/50
80/80 [==============================] - 0s 2ms/step - loss: 0.3862 - accuracy: 0.8566
Epoch 50/50
80/80 [==============================] - 0s 2ms/step - loss: 0.3859 - accuracy: 0.8572

In [33]:
prd = ann.predict(x_test)

63/63 [==============================] - 0s 2ms/step

In [34]:
prd

array([[0.12279761],
       [0.12279761],
       [0.12279761],
       ...,
       [0.59971464],
       [0.16530511],
       [0.12279761]], dtype=float32)

In [35]:
prd1 = ann.predict(x_train)
prd_data1=[]
for i in prd1:
    if i[0] > 0.5:
        prd_data1.append(1)
    else:
        prd_data1.append(0)

250/250 [==============================] - 0s 1ms/step

In [36]:
prd = ann.predict(x_test)
prd_data=[]
for i in prd:
    if i[0] > 0.5:
        prd_data.append(1)
    else:
        prd_data.append(0)

63/63 [==============================] - 0s 1ms/step

In [37]:
prd_data

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 ...]

In [38]:
from sklearn.metrics import accuracy_score

In [39]:
accuracy_score(y_test,prd_data)*100

85.9

In [40]:
accuracy_score(y_train,prd_data1)*100

85.7

In [41]:
prd3 = ann.predict([[0.433879,-0.047942,-0.564197,-0.660018,-0.695982,0.324119,0.807737,-1.547768,-1.030670,-1.013811]])
prd_data=[]
for i in prd3:
    if i[0] > 0.5:
        prd_data.append(1)
    else:
        prd_data.append(0)
prd_data

1/1 [==============================] - 0s 102ms/step

[0]